/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPasskeyManager,
  IPasskeyManagerInterface,
} from "../IPasskeyManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "encodedId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "publicKeyX",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "publicKeyY",
        type: "uint256",
      },
    ],
    name: "PasskeyAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "encodedId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "publicKeyX",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "publicKeyY",
        type: "uint256",
      },
    ],
    name: "PasskeyRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_encodedId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "publicKeyX",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "publicKeyY",
        type: "uint256",
      },
    ],
    name: "addPasskey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_encodedId",
        type: "string",
      },
    ],
    name: "removePasskey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPasskeyManager__factory {
  static readonly abi = _abi;
  static createInterface(): IPasskeyManagerInterface {
    return new utils.Interface(_abi) as IPasskeyManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPasskeyManager {
    return new Contract(address, _abi, signerOrProvider) as IPasskeyManager;
  }
}
